# Generated by Django 3.2.4 on 2021-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes3',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='main.ingredients3'),
        ),
        migrations.DeleteModel(
            name='recipe_ingredients3',
        ),
    ]
