# Generated by Django 3.2.4 on 2021-07-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210702_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes3',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipes3',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
