# Generated by Django 3.2.4 on 2021-07-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recipe_ingredients3'),
    ]

    operations = [
        migrations.CreateModel(
            name='or_ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_ingredient', to='main.ingredients3')),
                ('or_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_ingredient', to='main.ingredients3')),
            ],
        ),
    ]
