# Generated by Django 3.2.4 on 2021-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ingredients',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
