# Generated by Django 3.2.4 on 2021-07-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recipes',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_ingredients',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ingredients', to='main.ingredients3'),
        ),
        migrations.AlterField(
            model_name='user_recipes',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recipe', to='main.recipes3'),
        ),
    ]
