# Generated by Django 3.2.4 on 2021-07-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210705_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredients3',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe_ingredients3',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipes3',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes3',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
