# Generated by Django 3.2.4 on 2021-07-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210707_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recipes',
            name='or_ingredient',
            field=models.BooleanField(default=False),
        ),
    ]
