# Generated by Django 3.2.4 on 2021-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210707_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_list',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grocery_list',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
