# Generated by Django 3.2.4 on 2021-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_user_recipes_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery_list',
            options={},
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
