# Generated by Django 3.2.4 on 2021-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_user_recipes_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recipes',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
    ]
