# Generated by Django 3.2.4 on 2021-08-04 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_user_recipes_disliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes3',
            name='checked',
            field=models.ManyToManyField(related_name='checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipes3',
            name='disliked',
            field=models.ManyToManyField(related_name='disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipes3',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
