# Generated by Django 3.2.4 on 2021-08-05 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_auto_20210804_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_recipes',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='user_recipes',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='user_recipes',
            name='liked',
        ),
        migrations.AddField(
            model_name='ingredients3',
            name='checked',
            field=models.ManyToManyField(related_name='ing_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='user_ingredients',
        ),
    ]
