# Generated by Django 3.2.4 on 2021-08-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210805_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients3',
            name='or_ing',
            field=models.BooleanField(default=False),
        ),
    ]
